### PR TITLE
Prevent login warning on PHP 5.6+

### PR DESCRIPTION
**Pull request by chris98**
Fix for ticket #1058

You might have to check my PR to make sure it's ok :P

### CODE REVIEW

**Comment by oldskool** [comment]
According to the [documentation](http://php.net/hash_equals), both arguments should be strings, so both should be typecast to avoid the error from moving to the second argument. In other words, change it to:

```php
return hash_equals((string)$a, (string)$b);
```

**Comment by chris98** [comment]
The second is the user password which will always be a string, even if nothing is entered, so that isn't a problem.

**Comment by oldskool** [comment]
@chris98 Well, it is currently. But it is an assumption to say it will always be that way. What if down the line we convert empty strings to null values somewhere? By typecasting the `$b` variable as well, you enforce it to be the proper type and avoid a similar bug to possibly appear in the future.

**Comment by chris98** [comment]
I don't really anticipate this changing anytime soon ;)

I'll leave this to the devs as to what they would like. Personally, I don't see any benefit from the additional cast.

**Comment by chris98** [comment]
I've updated the PR and it's now casting both of them.

**Comment by oldskool** [comment]
@chris98 Thanks, merged. This way we ensure that the input is always what the function expects it to be, so it gives more consistency.

**Comment by franzliedke** [comment]
This has been merged into the wrong branch. ;)
master should be kept clean in case of urgent security releases needing to be made.

Before we merge any further PRs, I will clean up the branches.

**Comment by oldskool** [comment]
@franzliedke Oh snap, sorry! :sob:

**Comment by franzliedke** [comment]
It's fine, though. If we're lucky, reverting is not necessary. ;)

**Pull request merged**
