### PR TITLE
Remove discontinued AOL IM

### PR DESCRIPTION
**Pull request by Quy**
#1127

### CODE REVIEW

**Comment by kierownik** [comment]
And remove them from the language files

**Comment by franzliedke** [comment]
Thank you! :raised_hands:

**Comment by philwareham** [comment]
Yahoo Messenger service ceased in July 2018 and MSN Messenger ceased 2013-2014 - could/should these also be removed from user profiles?

Maybe they could be replaced by Twitter/Mastodon/Instagram/etc. (depends whether you think those services are worth promoting I guess)?

**Comment by franzliedke** [comment]
@philwareham Sure. Would you be so kind and send a PR for these two?

**Comment by philwareham** [comment]
@franzliedke no problem - will send a couple of PR's later this week (one removing the obsolete services and one adding social channels). Cheers!

**Pull request merged**
