### PR TITLE
[1.5.8] Antispam plugins

### PR DESCRIPTION
**Pull request by franzliedke**
Antispam functionality is a feature that we cannot yet build into the core (because this would probably lead to bots targeting our functionality specifically), but still everybody needs it.

That's why I thought: why not build a simple antispam plugin system? That would allow people to add anti-spam features by dropping one file into the `antispam/` folder. These would then be called automatically at certain important points, such as during registration or when making posts.

Anti-spam mods would then be super easy to install: often simply by copying a file into a directory. (I've heard about forum admins that don't want to install mods, which I can understand, because they make upgrading a pain.)

Due to the urgency of fighting against spam, I deemed this important enough to include in 1.5.x.

What we need to decide on is where to include the hooks for antispam plugins. After looking at some of the anti-spam mods out there, I'm currently planning on the following:

- register.php and post.php:
  - before the header is included (so that `$required_fields` can be populated)
  - at the end of the form (so that other form fields can be inserted)
  - during validation (so that the submitted values can be checked)

Others? Probably viewtopic.php (quick post)...

### CODE REVIEW

**Comment by sevendays** [comment]
First of all, __thanks__! 

I'd include `login.php` to the list, in the case one wants to block access or show captchas after X login attempts.

I use `viewtopic.php` within the [akismet antispam mod](http://fluxbb.org/resources/mods/gamezoo-akismet/) only to show the "mark post as spam" option. But that's not really a must have.

One other checkpoint could be the user properties: some spammers just register and use the signature to put "dangerous" links.

**Comment by franzliedke** [comment]
Yeah, login.php is a good idea.

I guess we need hooks in the user profile anyway: Mods like the StopForumSpam mod try to add buttons there to easily report a user as spammer / delete them.

**Comment by GWRon** [comment]
Regarding your current commit attached to this issue:

```php
	foreach ($flux_antispam as $plugin)
		$plugin->$name();
```
does not check for the availability of the function. As the plugins do not derive from a parental class, there is no guarantee for the "$name" to be a callable/existent function.

@ hooks:
Couldn't you just do it like an event system? So calling _Hook("login.startup") will loop through all registered hooks and call all "login.startup" ones.

I do not know how much impact it has if you have 40-50 hook-lookups (hash maps). If it is up to none, there should be up to no limit regarding added hooks to the whole system - this eases the process of integrating modules/addons - and is surely already a topic which was discussed years ago.

If you do not like the name "hook" for this: hooks are the same thing just with different naming scheme.

@ locations
every user interaction should be providing hooks - so you could in theory provide a bot a different page than normal users - so bots just think they were successful at posting their spam. If you block bots you will more or less come into contact with human bot-assistants (manual registrations with manual question lookup or recaptcha solvers).

**Comment by franzliedke** [comment]
I actually have a base class lying around on my computer, that will simply have an empty method for every hook we'll define. But that will have to wait for the final list of hooks.

Yeah, since the code relies on globals all over the place anyway, I was just gonna go without passing anything to the methods. The plugin classes wil simply have to access the globals.

This is really just a band-aid.

**Comment by GWRon** [comment]
Creating "stub functions" is surely an alternative solution to the dynamic approach of checking for the existence of a callable function. 

The callable thing of course leads to more checks but saves on memory as the modules then just contain what they need to contain (and do not include the things of the parental "struct"). Extending from a base class on the other side defines needed functions on the side of the base class (_"abstract"_ defined functions). But it needs a special implementation for each kind of "module" and does not allow for __one__ module doing multiple things. I understand that a "antispam" module should only care for this, but there might be other helper modules which assist here and there - and in that case you would start up creating multiple interfaces extending each other (iAntiSpam, iAdminPanel, iWhatever) just to create the mix you need for your wonderful module.

Think your approach might fit better in this case.

A pitty that v1.x will surely leave the spotlight once 2.x comes along ... I would have preferred a cleaned up fluxx 1.5. But I do not want to derail the discussion.

**Comment by franzliedke** [comment]
I've now added a base class and started adding hooks, first just to register.php. This is already enough for my recaptcha implementation, so I'm confident we can do many things with just a few hooks.

**Comment by GWRon** [comment]
Of course you should be able to do many things - but I somehow think this limits the flexibility of a hook system without a real need for limitation.

You use __flux_antispam_hook('register_validate');__ instead of a more versatile __flux_hook('register_validate');__ which then asks all registered "hook-collections". For now you include the "antispam" script in _common.php_ . Maybe just include a "hooks.php"-script there. This script then includes all hook-collections on its own (or loops through a module-directory to ask the modules to register for hooks - if you want to keep it even more dynamic). That "hooks.php"-script then defines the __flux_hook($param)__  function. This function then calls the individual functions of the scripts like "antispam".

Sorry if I wrote a bit confusing ... So I allow myself to sum it up:
- generic hook-script instead of individual "include myscript.php" in common.php
- generic script then contains calls to individual scripts like the antispam one
- when the hook is called, it iterates over the individual scripts

This avoids the need to add another hook to "register.php" at the same position as soon as you want to introduce some more functionality (think of gamification with "badges" for specific things ... or advanced notification systems). You end up having a generic hook-function caring for everything

Hmm ... I am sure that googling for "hook systems php" will come up with way prettier descriptions and explanations than I can come up with.

**Comment by franzliedke** [comment]
I know. We had all of this in v1.3. But I don't want to introduce a full-blown hook system in 1.5 now, because I want to focus on v2.0.

I just want antispam stuff to be easy to install and maintain.

That said, the community would obviously enjoy this. I'll keep the names generic, but will only introduce antispam-related hooks for now, to keep the changes in the upcoming version small.

**Comment by GWRon** [comment]
It is fully up to you, didnt want to create trouble regarding hooks. And of course it is up to you what to favor regarding focus. Think there will be some time needed to pass until people will switch to 2.0 (teething problems / Kinderkrankheiten). Did not even check how to handle that "composer" parts on a non-root-server or webhosting without terminal access ... but I assume that there are ways to do that there. Sorry for derailing the discussion.

Thanks for keeping things "generic". Will probably help either one or the other forum admin.

**Comment by franzliedke** [comment]
I just wonder what to call the "antispam" folder now. It obviously cannot be "plugins". Meh,,,

**Comment by GWRon** [comment]
It is just a "plugin" as it is only called via hooks. It is not directly connected to the core or so - which makes it a "plugin" (or "extension" or "hookListener" or whatever).

It really gets a "plugin" as soon as a hook-collector traverses through a plugin directory scanning for potential hook listeners ... which you wont do, as you manually do a __include_once("antispam.php")__ in your hook-script.

For now a directory "hookscripts" would fit well ...  Feel free to use some kind of "cache" to avoid traversing directories each time (the same way other caches are used in the admin panel) - or keep it easy-peasy for now and hardcode the includes like you suggested in your earlier commits of this issue.

**Comment by Quy** [comment]
Why not the `plugins` directory? Either prefix the filename with a P_ or when reading the directory exclude filenames prefixed with AMP_ and AP_.

**Comment by sevendays** [comment]
Plugins have another way of doing things. I'd make a "hooks" directory to avoid confusion.

**Comment by franzliedke** [comment]
Okay, folks. How does this look now?

I've updated the implementation so that addons (that's what they'll be called) will have to register their callbacks for hooks themselves in the `register()` method. This way, we don't end up with countless methods in the addon base class (one for each hook).

All that's left is hooks in all relevant places. The current two hooks already allowed me to implement a fully functional Recaptcha addon.

**Comment by GWRon** [comment]
First of all: it seems you did it nearly exactly how I thought of... except the "payload" data object passed to each hook listener.

Did you think of checking "callability" during __bind()__ of a callback? Dunno how much "dynamism" will be used, so things might not be existent during bind but later on... hmm if the system just trusts the addon devs doing the right things, it should not be needed. But better talked about something than regretting it at a later stage.


Another useful thing: instead of traversing through the addons directory, a automagical created "activatedAddons.php" could be used. This file only includes addons the admin enabled. Within admin panel you could then have your "addons traversal" and some simple __[x] activate "ModuleName"__-Checkboxes (previously activated ones should be preselected of course). Shouldnt be that tricky to code.
Of course this is not that needed, if we talk about 1-2 addons, but file access can be expensive, so traversing through directories should be avoided. The expense of a "activatedAddons.php" file access is of course to include in the consideration.
So to keep things "easy", such a file could be postponed to a later stage.


Some notes:
```php
class flux_addon_manager
...
	function load()
...
			include $addon_file;
...
```
__include__, not __include_once__? Is this because you also __require__ instead of __require_once__ ? As the system does not include a template file there, I would suggest to only do things __*_once__.


__bind()__ allows duplicates - intended?:
```php
	function bind($hook, $callback)
...
		$this->hooks[$hook][] = $callback;
```



@ latest commit (instantiation move)
__flux_addon_manager__ is some kind of "singleton" (without explicit notation), so I think it should be instantiated right in the addons-class-file. Things assume that the global is created successfully, they should not need to know that "common.php" has to get included to make the global existent. Just include "addons.php" and the global should be there. So the "old variant" makes more sense to me. But yes, both variants do their job.

IF __flux_addon_manager__ is planned to be a singleton, it should check if it is already existent before creating a new one (and making registered hook callbacks obsolete).

**Comment by franzliedke** [comment]
For everyone: I've now uploaded my example reCAPTCHA addon [here on GitHub](https://github.com/franzliedke/fluxbb-new-recaptcha). I believe this can serve as a reference implementation.

---

@GWRon Thank you very much for the feedback - let me address your points one-by-one:

**Payload object:** Given FluxBB uses globals all over the place, I believe they're not necessary in this bare-bones implementation.

**Checking "callability":** Hmm, I didn't think this was urgently needed. How would you implement the check?

**Admin page for activation of addons:** Sounds like a very good idea for the next version. I'm not anticipating too many of these addons for now, so we shouldn't hit scaling problems very soon. Let's see how the community adopts these and then maybe introduce something along these lines in v1.5.9.

**include_once:** I didn't use this, because `include` is slightly faster and we already make sure `load()` is only called once. I don't really have a strong opinion on this, though.

**bind() and duplicates:** Are you referring to multiple listener registrations from one addon. Then yes, I don't care that much and trust in the responsibility of the mod developers.

**Manager singleton:** From an engineering perspective, you're probably right. Given how FluxBB is used and that these most certainly are not reusable components, I don't think it's a problem. My reasoning for moving the instantiation to `common.php` was so that `addons.php` only contained classes and no procedural code. Mixing those should be avoided in my opinion.

---

Thanks, everybody, for this very focused discussion. I'm very much enjoying this.

**Comment by GWRon** [comment]
@ callable
__is_callable()__, __function_exists()__ and __method_exists()__.
http://php.net/manual/de/function.is-callable.php
http://php.net/manual/de/function.function-exists.php
http://php.net/manual/de/function.method-exists.php

Of course they are not failsafe, but maybe they add a bit of assistance.


@ Payload
Of course you do not need to have it used for now, but just preparing things might come in handy somewhen (same for a return value / resultCode). Depending on whether you pass the payload by reference (just the pointer and therefor make it modifyable) or let the functions return the payload ("passthrough" modification). I would prefer a reference as it just looks cleaner to me.
BUT as php complains about references when not passing a previously created variable (like __hook($key, new Array())__) you would have to create a specific payload variable first and use it then (__$data = new Array; hook($key, $data);__).

@ include_once
Yes, it adds a bit to workload - but the __load()__ function and the duplicate-issue just shows why there might come up unforseen situations in which the addons get loaded multiple times. For now I do not see a certain situation, so there is no need for __*_once__ now. Maybe it is my personal style to favor them because things will get opCached at the end and so "performance" of raw code is less important than "logic". Like said, currently I do not see a logic flaw, so just keep includes/requires as they currently are.

@ bind() 
Yes I meant exactly that beaviour as you just append to the array. Some kind of hash-map-array (__$array["myobject-callback"] = $callback;__) would get rid of that - or manually check for existence of the $callback in that array during the bind-process. Binds do not get called thousands of time for a callback, so this is a one-time-process (maybe worth, to add, maybe not - this is your decision).


Back to "where to put the hooks to".

**Comment by Quy** [comment]
In `verify_user_response()`, it should check for a value in `$_POST['g-recaptcha-response']` before sending the request.

**Comment by franzliedke** [comment]
Thanks, @Quy. Done.

So, folks, where do we need hooks?

**Comment by GWRon** [comment]
- Before outputting the whole page (to manipulate end result)
- Before / After processing a posting in a thread (eg. to enable "[hide]"-tags which only show if you have responded in the thread, or to enable "gamification")
- Before / After registration (also verification)
- On login / logout
- On password reset
- On profile change
- On a moderation-action (deletion, moving ...)
- On "mark topics read"
- ...

Normally I would say: on nearly all user interactions, the portions outputting html and the functions modifying data.

The last one would provide a simple method to hook into eg. "bbcode" parsing. If you would pass data, you could eg. let hooks extend the bbcode-array. Or just let them handle things by passing the text to "bbcodify".
In this example there might be multiple addons doings similar bbcodes, so it is up to the admin to install non-conflicting things (or live with one of the addons not working properly as eg. the bbcode is no longer in the text). 

An example for "post"-content-parsing would be a hook which filters badwords (i know, this is hardcoded already) or which auto-replaces links with videoplayers.

**Comment by franzliedke** [comment]
Okay, I added all hooks that I think are necessary for antispam stuff.

Last question: Do we need a hook in include/common.php? For general stuff. The Bad Behaviour mod from Smartys did some checks in there.

Okay, I just saw @GWRon's post. I'll add some more tomorrow.

**Comment by GWRon** [comment]
Do not forget to have some kind of hooks.txt listing available hooks...will ease things later on.

Am 18. Januar 2015 19:19:26 MEZ, schrieb Franz Liedke <notifications@github.com>:

**Comment by franzliedke** [comment]
For the next version, I only want hooks for antispam-related stuff. To try it out, see how it gets adopted, what works and does not etc.

When that works out as expected, we can add more hooks where it makes sense. So, are any of the ones you proposed important for antispam related stuff? I took a look at quite a few antispam mods and those should be well-suited with the hooks I added.

I'll add the list of hooks to the documentation, I'll have to write a bit anyways. Unless one of you wants to do that. =)

**Comment by GWRon** [comment]
None of the things i listed should be needed in addition to yours to make antispam work. Only posting, login and registration should be needed for it.

My list was more a todo list.

Concerning documentation... Once you are into writing already I suppose nobody of us wants interrupt your flow :-).

Am 18. Januar 2015 19:27:39 MEZ, schrieb Franz Liedke <notifications@github.com>:

**Comment by Quy** [comment]
`profile.php` for StopForumSpam to report and delete the user.

**Comment by Studio384** [comment]
I would add a hook to the "Request password"-form. Also, I can't be the only one who thinks that 1.5.7 is getting ridiculous for a x.x.1 release... Do we follow something like semantic versioning? Because in that case, we're messing up a lot... Breaking support with old requirements (PHP4.4 and IE6), some rather obvious style changes, new features (promotion, forum creating, etc) a (partial) hook system...

Anyway, back on topic: how are these things going to be handles on FluxBB.org? We have a "Plugin" section, but it's not functional at the moment... They aren't realy modifications either...

**Pull request merged**
