### PR TITLE
#1022 Drop support for PHP 4.4.0 - 5.2.X

### PR DESCRIPTION
**Pull request by Studio384**
Please go through it to check if this is correct or if I missed out on some stuff. Obviously, as long as the actual minimum requirement is in discussion, this shouldn't be merged yet (unless you agree for this). :)

### CODE REVIEW

**Comment by Quy** [comment]
Update `forum_setcookie()`, `maintenance_message()`, and `redirect()`.

**Comment by adaur** [comment]
I'm not sure we want to push this into master. Maybe a 1.6-branch.

**Comment by oldskool** [comment]
This should definitely not go in master as this will potentially break a lot of existing 1.5 installs.
@franzliedke Could you add a 1.6 branch? Then it can be targeted to this.

**Comment by Studio384** [comment]
> I'm not sure we want to push this into master. Maybe a 1.6-branch.

> This should definitely not go in master as this will potentially break a lot of existing 1.5 installs.
@franzliedke Could you add a 1.6 branch? Then it can be targeted to this.

Indeed, I've asked for it in another pull request too. Anyway, at least you can already give feedback on all these changes. But they should indeed not go into master.

**Comment by Quy** [comment]
As of `5.0.0`, there is a `get_as_float` parameter so this can be updated.
```
function get_microtime()
{
	list($usec, $sec) = explode(' ', microtime());
	return ((float)$usec + (float)$sec);
}
```

**Comment by franzliedke** [comment]
Indeed. `microtime(true)` makes `get_microtime()` obsolete.

However, I have already implemented most of these on a private branch on my computer. I'll have to push that soon, I guess.

**Pull request closed without merging**
