### PR TITLE
Get rid of inline script for redirects

### PR DESCRIPTION
**Pull request by franzliedke**
This is another shot at fixing [this issue](https://fluxbb.org/development/core/tickets/1029/).

Quy also suggested this approach.

/cc @Quy @adaur @chris98

### CODE REVIEW

**Comment by franzliedke** [comment]
Whoopsie. Fixed the URL.

**Comment by Quy** [comment]
This applies to `admin_maintenance.php` too.

**Comment by chris98** [comment]
I must be honest, I don't like this approach as much because it's mixing HTML with PHP. That said though, I don't really see how it could be better under the circumstance as we seem to have tried all the pure PHP methods :(

**Comment by franzliedke** [comment]
Okay, I just pushed some final commits that take care of the following:

- admin_maintenance
- Fallback links in case the automatic redirect fails (e.g. because of `<meta>` tag appearing in the body)

**Comment by franzliedke** [comment]
I tested it, and it works for me. If you have the chance, please review once more, so I can release this afternoon. :)

**Comment by Quy** [comment]
LGTM :thumbsup:

**Comment by franzliedke** [comment]
Squashed this in 04cafe815432b86d0f11677153ecf0359cf031db. Thanks for your help, folks!

**Pull request closed without merging**
