### PR TITLE
Updated JS redirect

### PR DESCRIPTION
**Pull request by chris98**
Hopefully I've done it correctly this time. If not, I'll pass the code through the ticket to avoid wasting more of your time.

### CODE REVIEW

**Comment by franzliedke** [comment]
Looks good. I'll go through this later tonight...

**Comment by chris98** [comment]
Hooray!

**Comment by franzliedke** [comment]
Thanks a lot!

**Comment by chris98** [comment]
No problem - glad it was useful =)

**Comment by Quy** [comment]
```
Notice: ob_end_clean(): failed to delete buffer. No buffer to delete in C:\xampp\htdocs\fluxbb159\db_update.php on line 1911

Warning: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\fluxbb159\db_update.php:1911) in C:\xampp\htdocs\fluxbb159\db_update.php on line 1912
```
Tested with Windows Firefox 41.0.2 in XAMPP.

**Comment by chris98** [comment]
Use @ob_end_clean() to fix this issue. It's because output buffering hasn't started when the script is calling it. But if no output is being made on the page anymore, do we need this?

Also - taking another look at that code and we should really change header() to redirect(). This is because if there is a large amount of headers() Firefox will send the message that the webpage has a redirect loop.

**Comment by Quy** [comment]
Same error after `Rebuilding index for post 960`.
```
Warning: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\fluxbb159\db_update.php:1811) in C:\xampp\htdocs\fluxbb159\db_update.php on line 1912
```

**Comment by chris98** [comment]
Ah ....

You tried with db_update.php. I assumed you did it with admin_maintenance.php. I've checked and there's an ob_start() on line 1625 which is inside a separate case statement. I'd move this to either line 687 or 1774 instead. I'd personally move it to 687 so I would be sure that it doesn't affect anything else.

I've taken another look at admin_maintenance.php too and we don't need ob_end_clean() or ob_start() there as no output is being made.

**Comment by Quy** [comment]
Per the Rebuild Index: 
```
If you are forced to abort the rebuild process, make a note of the last processed post ID and enter that ID+1 in "Starting post ID" when/if you want to continue ("Empty index" must not be selected).
```
So there should be output: `echo '<p><span>'.sprintf($lang_admin_maintenance['Processing post'], $cur_item['id']).'</span></p>'."\n";`

With this commit:
```
Firefox has detected that the server is redirecting the request for this address in a way that will never complete.
```

**Comment by chris98** [comment]
Oops. I forgot to reply to this.

To fix that, you need to use redirect() instead of header()

**Comment by adaur** [comment]
Can you do a PR @chris98 ?

**Comment by Quy** [comment]
It is a no go too with redirect() when `Redirect time` is set to 0.

**Comment by franzliedke** [comment]
Woah, I dug into this now and this is super complicated, unless I'm missing something.

We have two choices, as far as I see:
- Use the `header()` approach, which means we lose the visible progress indication ("Processing post number one" etc.)
- Don't use that method, but find a way not to use an inline script for redirecting.

**Comment by franzliedke** [comment]
Hmm, do we even need the inline script in db_update.php? After all, it already renders a meta tag for automatic redirection...

**Comment by Quy** [comment]
I suggested that in the [url=http://fluxbb.org/development/core/tickets/1029/]ticket[/url]. I can do a test again to confirm.

**Pull request merged**
