### PR TITLE
some cosmetic changes

### PR DESCRIPTION
**Pull request by Allec-Bernz**

### CODE REVIEW

**Comment by oldskool** [comment]
Could you [squash your commits](https://help.github.com/articles/about-git-rebase/) into one? And also, can you target the `1.5-next` branch instead of `master`? Thanks!

**Comment by franzliedke** [comment]
:+1: Please do as @oldskool wrote, then we can merge.

**Comment by Allec-Bernz** [comment]
I doubt that I can do it, there is a simpler way?

**Comment by oldskool** [comment]
@Allec-Bernz It might look difficult, but it's really not that hard.
From your terminal/git bash, run `git rebase -i head~3`, that should show something like this:

```
pick 309973d some cosmetic changes
pick c1a3e81 some cosmetic changes
pick 1a6cf67 some cosmetic changes
```

Simply change the last two `pick`'s to `fixup` or `f`, so you'll get this:

```
pick 309973d some cosmetic changes
fixup c1a3e81 some cosmetic changes
fixup 1a6cf67 some cosmetic changes
```

Then save and quit your editor and push the branch to your fork again (with force, because you "rewrote history"): `git push -f`.

Finally, open up a new PR, but instead of chooing `master` as the target (in the branches dropdown), choose `1.5-next`.

**Comment by Allec-Bernz** [comment]
Thanks a lot!

**Comment by oldskool** [comment]
Closing in favor of #175

**Pull request closed without merging**
