### PR TITLE
some cosmetic changes in styles

### PR DESCRIPTION
**Pull request by Allec-Bernz**

### CODE REVIEW

**Comment by Allec-Bernz** [comment]
Oops, it looks like I have done something wrong ...

**Comment by oldskool** [comment]
Hmm, yeah looks like it's rebased on master. But the good news is you're close now. This final step should do it: `git rebase 1.5-next`.

**Comment by franzliedke** [comment]
Or, if that does not work, create a new branch off of our "1.5-next" branch, then reapply [this commit](https://github.com/Allec-Bernz/fluxbb/commit/caff8e31b638a3d6beaa914841a01ab139959810) to that branch and send a new pull request. ;)

**Comment by Allec-Bernz** [comment]
Thanks!

**Pull request closed without merging**
