### PR TITLE
#1019: Move forum_list_plugins to common_admin.php

### PR DESCRIPTION
**Pull request by Quy**

### CODE REVIEW

**Comment by franzliedke** [comment]
Is the move necessary? I'd rather keep changes small in the next release. ;)

**Comment by Quy** [comment]
@franzliedke It is not necessary, however, it is an easy (small) change affecting only 2 files that can be done or not if upgrading manually.

@GWRon If it is okay with Franz, I will implement your suggestions.

**Comment by franzliedke** [comment]
Sounds good.

**Comment by Quy** [comment]
Here is the improved code. LGTY?
```
function forum_list_plugins($is_admin)
{
	$plugins = array();

	$d = dir(PUN_ROOT.'plugins');
	if ($d)
	{
		while (($entry = $d->read()) !== false)
		{
			if (!is_dir(PUN_ROOT.'plugins/'.$entry) && preg_match('%^AM?P_(\w*?)\.php$%i', $entry))
			{
				$prefix = substr($entry, 0, strpos($entry, '_'));

				if ($prefix == 'AMP' || ($is_admin && $prefix == 'AP'))
					$plugins[$entry] = substr($entry, strlen($prefix) + 1, -4);
			}
		}
		$d->close();

		natcasesort($plugins);
	}

	return $plugins;
}
```

**Comment by GWRon** [comment]
Why the plugin-list sort? I know that it might come handy somewhen - does the previous "glob"-thing sort it automatically or do you introduce a new feature here?

Do not misunderstand me: I think adding the sorting is a good step.

Regarding `if ($d)` - we could get rid of the whole "{ ... }" portion by doing a
```php
 $d = dir(PUN_ROOT.'plugins');
 if (!$d) return $plugins;

 while (($entry = $d->read()) !== false)
```

The bracket-variant is only useful if you intend to do something more after the while-loop, which isnt the case for now.

**Comment by Quy** [comment]
A sort is required to sort on filenames without the prefix (`AMP / AP`).

**Comment by GWRon** [comment]
Just did not see that it was there in the original source ... so ignore my "suggestion"

**Pull request merged**
