### PR TITLE
Update Russian time zones

### PR DESCRIPTION
**Pull request by c-e-p-x-u-o**
https://en.wikipedia.org/wiki/Time_in_Russia

### CODE REVIEW

**Comment by franzliedke** [comment]
Thanks again!

**Comment by Squatter-1** [comment]
Hi! Stopforumspam has blocked all addresses
It is not possible to register on your website (fluxbb.org).
All ip range of my provider is in the blacklist stopforumspam.com
 
46.164.192.0/18
83.139.128.0/18
92.244.224.0/19
94.141.32.0/19
 
Wrote ten applications in stopforumspam.com. None of the ip is not unlocked for 3 days.
 
stopforumspam is an outdated garbage that reduces the number of your community.
 
Please solve this problem.

**Comment by franzliedke** [comment]
Stopforumspam saves my sanity. Please take your complaint to them.

**Comment by Squatter-1** [comment]
**franzliedke**
They leave all complaints unanswered for.

3 days I can not register fluxbb.org

Give an account, please, if it's not too much trouble

**Comment by c-e-p-x-u-o** [comment]
@Squatter-1: I don't want to knot anything about this. Please do not offtop here!

**Comment by Squatter-1** [comment]
Great! Friendly you guys))

**Comment by c-e-p-x-u-o** [comment]
You can open separate issue. But, please, stop disturbing me.

**Comment by Squatter-1** [comment]
Excuse me.

**Comment by oldskool** [comment]
Thanks for your contribution @c-e-p-x-u-o !
I removed all the off-topic posts here, as this is not a support thread.

**Comment by c-e-p-x-u-o** [comment]
Thank you.

**Pull request merged**
